version: "3.9"
services:
  dev:
    container_name: dev
    image: ubuntu:latest
    command: sleep infinity

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns: 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8081:80/tcp"
      - "4433:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - './pihole/etc-pihole/:/etc/pihole/'
      - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    mem_limit: 1000m

  ## Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    dns: 127.0.0.1
    ports:
      - "9090:9090/tcp"
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    mem_limit: 1000m

  satisfactory:
   container_name: 'satisfactory'
   hostname: 'satisfactory-server'
   image: 'wolveix/satisfactory-server:latest'
   ports:
    - '7777:7777/udp'
    - '15000:15000/udp'
    - '15777:15777/udp'
   environment:
    - DEBUG=false
    - MAXPLAYERS=8
    - PGID=1000
    - PUID=1000
    - SKIPUPDATE=false
    - STEAMBETA=true
   restart: unless-stopped
   volumes:
    - '/home/rojo/dev/satisfactory:/config'

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./cloudflare-ddns/config.json:/config.json
    restart: unless-stopped

  discord-musicbot:
    build: ./discord-musicbot
    image: discord-musicbot:latest
    container_name: discord-musicbot
    restart: unless-stopped
    ports:
      - '80:3000/tcp'
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./discord-musicbot/botconfig.js:/usr/src/app/botconfig.js:ro

  lavalink:
    image: fredboat/lavalink:dev
    container_name: lavalink
    hostname: lavalink
    restart: unless-stopped
    ports:
      - "8000:80/tcp"
      - "8000:80/udp"
    networks:
      - lavalink-net
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro

  discord-jmusicbot:
    build: ./discord-jmusicbot
    image: discord-jmusicbot:latest
    container_name: discord-jmusicbot
    restart: unless-stopped
    volumes:
      - ./discord-jmusicbot/config.txt:/usr/src/JMusicBot/config.txt:ro

  discord-f1x:
    build: ./discord-f1x
    image: discord-f1x:latest
    container_name: discord-f1x
    restart: unless-stopped
    volumes:
      - ./discord-f1x/.env:/usr/src/f1x/.env:ro

  ftpgrab:
    image: crazymax/ftpgrab:latest
    container_name: ftpgrab
    volumes:
      - ./ftpgrab/db:/db:rw
      - ./ftpgrab/download:/download:rw
      - ./ftpgrab/ftpgrab.yml:/ftpgrab.yml:ro
    environment:
      - "TZ=Europe/Berlin"
      - "SCHEDULE=*/30 * * * *"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    restart: always 

networks:
  lavalink-net:
