version: "3.9"
services:
  dev:
    container_name: dev
    image: ubuntu:latest
    command: sleep infinity

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns: 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
    volumes:
      - './pihole/etc-pihole/:/etc/pihole/'
      - './pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    mem_limit: 1000m

  ## Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    dns: 127.0.0.1
    ports:
      - "9090:9090/tcp"
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    mem_limit: 1000m

  # ## Elasticsearh
  # es01:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
  #   container_name: es01
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es02,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data01:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - elastic
  # es02:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
  #   container_name: es02
  #   environment:
  #     - node.name=es02
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es03
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data02:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic
  # es03:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
  #   container_name: es03
  #   environment:
  #     - node.name=es03
  #     - cluster.name=es-docker-cluster
  #     - discovery.seed_hosts=es01,es02
  #     - cluster.initial_master_nodes=es01,es02,es03
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - data03:/usr/share/elasticsearch/data
  #   networks:
  #     - elastic

  satisfactory:
    container_name: satisfactory
    build: ./satisfactory
    restart: always
    ports:
      - 15000:15000/udp
      - 15777:15777/udp
      - 7777:7777/udp
    volumes:
      - '/home/rojo/dev/satisfactory:/home/steam/Satisfactory-dedicated:rw'
