#!/usr/bin/sh

thedate=$(date +"%Y%m%d%H%M")
thefolder=download
thelog=rotate.log

# Create logfile
test -f $thelog || touch $thelog

# Archive folder
#echo ${thedate}
zip -r "${thedate}.zip" $thefolder | tee -a $thelog

# Delete files older than 30 days
find . -type f  -mtime +10 -iname "*.zip" | xargs rm -f | tee -a $thelog

