global:
  scrape_interval: 5s

scrape_configs:
- job_name: silver_node_metrics
  static_configs:
  - targets: ['10.10.10.20:9100']

- job_name: traefik_metrics
  static_configs:
  - targets: ['traefik:8079']
